import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';

const OrderTracking = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [order, setOrder] = useState(null);
    const [loading, setLoading] = useState(true);
    const [isDetailsOpen, setIsDetailsOpen] = useState(false);

    useEffect(() => {
        if (!id) {
            alert("No Order ID provided.");
            navigate('/dashboard');
            return;
        }

        const fetchOrder = async () => {
            const { data, error } = await supabase
                .from('orders')
                .select('*')
                .eq('id', id)
                .single();

            if (error) {
                console.error("Error fetching order:", error);
                if (error.code === 'PGRST116') {
                    alert("Order not found");
                    navigate('/dashboard');
                }
            } else {
                setOrder(data);
            }
            setLoading(false);
        };

        fetchOrder();
        const interval = setInterval(fetchOrder, 5000); // Polling for realtime

        return () => clearInterval(interval);
    }, [id, navigate]);

    if (loading) return <div className="flex h-screen items-center justify-center bg-gray-100 text-slate-500">Loading order...</div>;
    if (!order) return null;

    // Logic for steps
    const steps = [
        { status: ['Paid', 'Request Received', 'Pickup Assigned'], title: 'Order Placed', icon: 'receipt_long' },
        { status: ['Washing', 'Ironing', 'Drying', 'Ironing/Folding', 'Packing', 'Processing', 'Ready for Delivery'], title: 'Cleaning', icon: 'local_laundry_service' },
        { status: ['Out for Delivery'], title: 'On The Way', icon: 'local_shipping' },
        { status: ['Completed'], title: 'Delivered', icon: 'check_circle' }
    ];

    let currentStepIndex = 0;
    const s = order.status;
    if (['Paid', 'Request Received', 'Pickup Assigned'].includes(s)) currentStepIndex = 0;
    else if (['Washing', 'Ironing', 'Drying', 'Ironing/Folding', 'Packing', 'Processing', 'Ready for Delivery'].includes(s)) currentStepIndex = 1;
    else if (['Out for Delivery'].includes(s)) currentStepIndex = 2;
    else if (['Completed'].includes(s)) currentStepIndex = 3;

    // Helper for Details Modal
    const getDeadline = (o) => {
        const created = new Date(o.created_at || new Date().toISOString()); // creating_at is auto-generated by supabase usually, using fallback
        let due = new Date(created);
        if (o.service === 'Wash & Fold') {
            due.setHours(due.getHours() + 6);
        } else {
            due.setDate(due.getDate() + 3);
        }
        return due;
    };

    const eta = getDeadline(order);
    const etaString = eta.toLocaleDateString([], { weekday: 'short', day: 'numeric', month: 'short' }) + ', ' + eta.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    const renderStagePill = (stage) => {
        let isDone = false;
        const logs = order.productionLogs || {};
        if (logs[stage] && logs[stage].done) isDone = true;

        // Handle combined stages if any, typically mapped to simple keys in logs
        // Logic simplified for React port

        return (
            <div className={`flex flex-col items-center gap-1 ${isDone ? 'opacity-100' : 'opacity-30'}`}>
                <div className={`size-6 rounded-full ${isDone ? 'bg-green-500 text-white' : 'bg-slate-200 text-slate-400'} flex items-center justify-center`}>
                    <span className="material-symbols-outlined text-[14px]">check</span>
                </div>
                <span className="text-[10px] uppercase font-bold text-slate-500">{stage.split('/')[0]}</span>
            </div>
        );
    };

    return (
        <div className="bg-gray-100 dark:bg-gray-900 font-display text-slate-900 dark:text-slate-100 antialiased overflow-hidden flex justify-center items-center min-h-screen">
            <div className="relative flex h-[100dvh] w-full max-w-md flex-col overflow-hidden bg-background-light dark:bg-background-dark sm:rounded-3xl sm:h-[calc(100vh-2rem)] shadow-2xl">
                {/* Header Overlay */}
                <div className="absolute top-0 left-0 right-0 z-20 flex items-center justify-between px-6 pt-12 pb-4 pointer-events-none">
                    <button onClick={() => navigate('/dashboard')} className="pointer-events-auto flex size-10 items-center justify-center rounded-full bg-white/90 dark:bg-black/40 backdrop-blur-sm shadow-sm text-slate-800 dark:text-white transition-transform hover:scale-105 active:scale-95">
                        <span className="material-symbols-outlined text-[20px]">arrow_back_ios_new</span>
                    </button>
                    <div className="pointer-events-auto px-4 py-2 bg-white/90 dark:bg-black/40 backdrop-blur-sm rounded-full shadow-sm">
                        <h2 className="text-sm font-bold tracking-tight text-slate-800 dark:text-white">Order #{order.id.slice(0, 8)}...</h2>
                    </div>
                    <button className="pointer-events-auto flex size-10 items-center justify-center rounded-full bg-white/90 dark:bg-black/40 backdrop-blur-sm shadow-sm text-slate-800 dark:text-white transition-transform hover:scale-105 active:scale-95">
                        <span className="material-symbols-outlined text-[20px]">more_horiz</span>
                    </button>
                </div>

                {/* Map Section */}
                <div className="relative h-[45vh] w-full shrink-0">
                    <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: 'url("https://lh3.googleusercontent.com/aida-public/AB6AXuDEFOJ74CeOcgobKKNIoS4DfYmqLln1IrDrIpokBCSj2cTB-LWTxjS1wlN9iqbFK5DrYAZJEuiOp9AhPwZNLG5zO-9Zt_3dYxMNkFyZD4lmIQSquk7ByghTkd_ih5xAgjrkDsPUZF-ueE2InDv6HUfiHT_PWsHOaWuADjcd4xBgl5LisQFekT19rUR7C0tNBXdTYz25czyJDDtDbH_5R5bmb_ptzRAZ1EroaHi0V8K3e8gJApJHxCrynm0qZ_ztF4BN4hur9PpqzHCq")' }}></div>
                    <div className="absolute inset-0 bg-gradient-to-b from-white/60 via-transparent to-transparent dark:from-black/60 pointer-events-none"></div>

                    {/* Animated Driver Marker (Visual only) */}
                    <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center">
                        <div className="relative flex items-center justify-center">
                            <div className="absolute size-16 rounded-full bg-primary/20 animate-ping"></div>
                            <div className="relative z-10 flex size-10 items-center justify-center rounded-full bg-primary border-2 border-white dark:border-slate-800 shadow-lg text-white">
                                <span className="material-symbols-outlined text-[20px]">local_laundry_service</span>
                            </div>
                        </div>
                        <div className="mt-2 rounded-lg bg-white/95 dark:bg-slate-800/95 px-3 py-1 text-xs font-bold text-slate-800 dark:text-slate-200 shadow-md backdrop-blur-sm">
                            5 min away
                        </div>
                    </div>
                </div>

                {/* Bottom Sheet */}
                <div className="relative -mt-6 flex flex-1 flex-col rounded-t-3xl bg-background-light dark:bg-background-dark shadow-float overflow-hidden z-10">
                    <div className="flex w-full items-center justify-center pt-3 pb-1">
                        <div className="h-1.5 w-12 rounded-full bg-slate-200 dark:bg-slate-700"></div>
                    </div>

                    <div className="flex-1 overflow-y-auto no-scrollbar px-6 pb-6 pt-2">
                        {/* Headline & ETA */}
                        <div className="mb-8 flex flex-col gap-2">
                            <div className="flex items-center justify-between">
                                <span className="inline-flex items-center rounded-full bg-accent-warm/20 px-3 py-1 text-xs font-bold text-[#D65A31] dark:text-[#FFB4A2]">
                                    <span className="mr-1.5 size-1.5 rounded-full bg-[#D65A31] dark:bg-[#FFB4A2] animate-pulse"></span>
                                    {order.status}
                                </span>
                                <span className="text-xs font-medium text-slate-400">Updated just now</span>
                            </div>
                            <h1 className="text-2xl font-bold leading-tight text-slate-900 dark:text-white">
                                Arriving Today, <span className="text-primary">4:00 PM</span>
                            </h1>
                        </div>

                        {/* Driver Card */}
                        <div className="mb-8 rounded-2xl bg-surface-light dark:bg-surface-dark p-4 shadow-sm border border-slate-100 dark:border-slate-700">
                            <div className="flex items-center justify-between gap-4">
                                <div className="flex items-center gap-4">
                                    <div className="relative size-12 shrink-0 overflow-hidden rounded-full border-2 border-white dark:border-slate-600 shadow-sm" style={{ backgroundImage: 'url("https://lh3.googleusercontent.com/aida-public/AB6AXuArakNJfjZFEyRzoLrScPzPa9-Gb50_pd9ayNRRArnl8C9MMQLE3n_H4FFRaXBqxKMMVtjr-BqiA1JcIsWTmXDHF55bcRDoLhSHm3MP9DPPPGDMcldGWW8kecY-XAL7Fs8UaS7SAHlMs8lZjlSD-dhvhlvxLSGXkmE7IlJK-zHI6-7nSJJuq5JhQH0F60SWcJ6eizgFkSplJWKtwqQEFe3mLSB5UDEBWM0V6MfyrI3q3iPCni2xKa9uPNxhzuDll348cNh6p9RrdstJ")', backgroundSize: 'cover', backgroundPosition: 'center' }}></div>
                                    <div className="flex flex-col">
                                        <p className="text-base font-bold text-slate-900 dark:text-white">Ralph</p>
                                        <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
                                            <div className="flex items-center text-yellow-500">
                                                <span className="material-symbols-outlined text-[14px] fill-current" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
                                                <span className="ml-0.5 font-semibold text-slate-700 dark:text-slate-300">4.9</span>
                                            </div>
                                            <span>•</span>
                                            <span>White Van</span>
                                        </div>
                                    </div>
                                </div>
                                <button className="flex size-10 items-center justify-center rounded-full bg-white dark:bg-slate-700 text-primary shadow-sm transition-colors hover:bg-slate-50 dark:hover:bg-slate-600">
                                    <span className="material-symbols-outlined text-[20px]">call</span>
                                </button>
                            </div>
                        </div>

                        {/* Timeline */}
                        <div className="relative pl-2">
                            <div className="absolute left-[19px] top-4 bottom-4 w-[2px] bg-slate-100 dark:bg-slate-800"></div>
                            {steps.map((step, index) => {
                                const isCompleted = index < currentStepIndex;
                                const isCurrent = index === currentStepIndex;
                                const isPending = index > currentStepIndex;

                                let iconBgClass = isPending ? 'bg-white dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 text-slate-300' : (isCompleted ? 'bg-primary text-white' : 'bg-white border-2 border-primary text-primary');
                                if (isCurrent && index === 0) iconBgClass = 'bg-primary text-white';
                                if (isCurrent && index !== 0) iconBgClass = 'bg-white border-2 border-primary text-primary';

                                return (
                                    <div key={index} className="group relative mb-8 grid grid-cols-[40px_1fr] gap-x-4">
                                        <div className="relative flex h-full flex-col items-center">
                                            <div className={`z-10 flex size-10 items-center justify-center rounded-full shadow-soft ${iconBgClass}`}>
                                                <span className="material-symbols-outlined text-[20px]">{step.icon}</span>
                                            </div>
                                            {index < steps.length - 1 && isCompleted && (
                                                <div className="absolute top-10 bottom-[-32px] w-[2px] bg-primary"></div>
                                            )}
                                        </div>
                                        <div className="pt-2">
                                            <h3 className={`text-base font-bold text-slate-900 dark:text-white ${isPending ? 'opacity-50' : ''}`}>{step.title}</h3>
                                            <p className={`text-sm text-slate-500 dark:text-slate-400 ${isPending ? 'hidden' : 'block'}`}>
                                                {isCurrent ? 'In Progress' : (isCompleted ? 'Completed' : 'Pending')}
                                            </p>
                                        </div>
                                    </div>
                                );
                            })}
                        </div>

                        <div className="mt-8 pb-4">
                            <button onClick={() => setIsDetailsOpen(true)} className="w-full rounded-xl bg-slate-100 dark:bg-slate-800 py-3 text-sm font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors">
                                View Order Details
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* Details Modal */}
            {isDetailsOpen && (
                <div className="fixed inset-0 z-50">
                    <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setIsDetailsOpen(false)}></div>
                    <div className="absolute bottom-0 left-0 right-0 sm:top-1/2 sm:left-1/2 sm:-translate-x-1/2 sm:-translate-y-1/2 sm:w-full sm:max-w-md sm:h-auto sm:rounded-2xl rounded-t-3xl bg-white dark:bg-surface-dark shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
                        <div className="flex justify-between items-center p-6 border-b border-slate-100 dark:border-slate-700">
                            <h3 className="text-xl font-bold text-slate-900 dark:text-white">Order Details</h3>
                            <button onClick={() => setIsDetailsOpen(false)} className="size-8 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center hover:bg-slate-200 dark:hover:bg-slate-600">
                                <span className="material-symbols-outlined text-slate-600 dark:text-slate-300">close</span>
                            </button>
                        </div>
                        <div className="p-6 overflow-y-auto space-y-6">
                            {/* ETA */}
                            <div className="text-center">
                                <p className="text-sm text-slate-500">Estimated Completion</p>
                                <p className="text-2xl font-bold text-primary">{etaString}</p>
                            </div>

                            {/* Driver Info */}
                            {order.driver && (
                                <div className="bg-surface-light dark:bg-slate-800 p-4 rounded-xl flex items-center gap-4">
                                    <div className="size-12 rounded-full bg-slate-200 flex items-center justify-center text-slate-400">
                                        <span className="material-symbols-outlined">person</span>
                                    </div>
                                    <div>
                                        <p className="text-xs font-bold uppercase text-slate-500 tracking-wider">{order.status === 'Out for Delivery' ? 'Delivery Courier' : 'Pickup Driver'}</p>
                                        <p className="font-bold text-slate-900 dark:text-white">{order.driver.name}</p>
                                        <p className="text-sm text-slate-500">{order.driver.phone}</p>
                                    </div>
                                </div>
                            )}

                            {/* Production / Items */}
                            {order.productionItems && order.productionItems.length > 0 ? (
                                <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-xl border border-blue-100 dark:border-blue-800">
                                    <div className="flex justify-between items-center mb-3">
                                        <p className="text-xs font-bold uppercase text-blue-600 dark:text-blue-400 tracking-wider">Production Output</p>
                                        <span className="text-xs font-bold bg-blue-100 text-blue-700 px-2 py-0.5 rounded">{order.productionCount || 0} Pcs Total</span>
                                    </div>
                                    <div className="mb-3">
                                        {order.productionItems.map((item, i) => (
                                            <div key={i} className="flex justify-between text-sm py-1 border-b border-slate-100 dark:border-slate-800 last:border-0">
                                                <span className="text-slate-600 dark:text-slate-300">{item.type}</span>
                                                <span className="font-bold text-slate-900 dark:text-white">x{item.qty}</span>
                                            </div>
                                        ))}
                                    </div>
                                    {order.productionNotes && (
                                        <p className="text-sm text-blue-800 dark:text-blue-200 italic border-l-2 border-blue-300 pl-2">"{order.productionNotes}"</p>
                                    )}
                                    <div className="mt-4 flex gap-1 justify-between">
                                        {renderStagePill('Washing')}
                                        {renderStagePill('Drying')}
                                        {renderStagePill('Ironing/Folding')}
                                    </div>
                                </div>
                            ) : (
                                <div className="bg-surface-light dark:bg-slate-800 p-4 rounded-xl">
                                    <p className="text-xs font-bold uppercase text-slate-500 tracking-wider mb-2">Service Details</p>
                                    {order.service === 'Wash & Fold' ? (
                                        <p className="font-bold text-lg text-slate-900 dark:text-white">{order.weight} KG (Wash & Fold)</p>
                                    ) : (
                                        <div>
                                            <p className="font-bold text-md text-slate-900 dark:text-white mb-2 flex items-center gap-2">
                                                <span className="material-symbols-outlined text-primary">dry_cleaning</span>
                                                Dry Clean Items
                                            </p>
                                            <div className="space-y-1">
                                                {Object.entries(order.items || {}).map(([item, qty]) => (
                                                    qty > 0 && (
                                                        <div key={item} className="flex justify-between text-sm py-1 border-b border-slate-100 dark:border-slate-700 last:border-0">
                                                            <span className="text-slate-600 dark:text-slate-300 capitalize">{item.replace(/-/g, ' ')}</span>
                                                            <span className="font-bold text-slate-900 dark:text-white">x{qty}</span>
                                                        </div>
                                                    )
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            )}

                            {/* Evidence */}
                            {order.evidence && (
                                <div className="space-y-2">
                                    <p className="text-xs font-bold uppercase text-slate-500 tracking-wider">Laundry Accepted</p>
                                    <div className="h-32 w-full bg-slate-100 rounded-xl flex items-center justify-center border-2 border-dashed border-slate-300">
                                        <div className="flex flex-col items-center text-slate-400">
                                            <span className="material-symbols-outlined">image</span>
                                            <span className="text-xs">Evidence Photo</span>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* Original Request Summary */}
                            <div className="border-t border-slate-100 dark:border-slate-700 pt-4">
                                <p className="text-xs font-bold uppercase text-slate-500 tracking-wider mb-2">Original Request</p>
                                <div className="flex justify-between items-center">
                                    <span className="text-sm text-slate-600 dark:text-slate-300">Total Billed</span>
                                    <span className="font-bold text-lg text-slate-900 dark:text-white">{new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(order.total)}</span>
                                </div>
                                <p className="text-xs text-slate-400 mt-1">{order.id} • {order.schedule}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            <style>{`
                 .no-scrollbar::-webkit-scrollbar {
                    display: none;
                }
                .no-scrollbar {
                    -ms-overflow-style: none;
                    scrollbar-width: none;
                }
             `}</style>
        </div>
    );
};

export default OrderTracking;
